/**
 * Layer type
 */
export type Layer = 'LAYER_1' | 'LAYER_2' | 'LAYER_3' | 'LAYER_4' | 'LAYER_GREEDY' | 'LAYER_VISUAL' | 'LAYER_PREEXISTING' | 'LAYER_LS' | 'LAYER_LS_STOCHASTIC' | 'LAYER_LS_CLASSIFICATION' | 'LAYER_LS_STOCHASTIC_NORMAL_PROB' | 'LAYER_LS_STOCHASTIC_BAYESIAN_PROB' | 'LAYER_LS_STOCHASTIC_BAYESIAN_PROB_MIXED' | 'LAYER_LS_STOCHASTIC_T_PROB'