export type Layer =
  | 'LAYER_1'
  | 'LAYER_2'
  | 'LAYER_3'
  | 'LAYER_4'
  | 'LAYER_GREEDY'
  | 'LAYER_VISUAL'
  | 'LAYER_BACKTRACKING'
  | 'LAYER_PREEXISTING'
  | 'LAYER_LS_STOCHASTIC_BAYESIAN_PROB'
  | 'LAYER_LS_CLASSIFICATION';
